name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      CONFIGURATION: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build \
            --configuration ${{ env.CONFIGURATION }} \
            --verbosity minimal \
            --no-restore 
      
      - name: Test
        run: |
          dotnet test \
            --configuration ${{ env.CONFIGURATION }} \
            --verbosity normal \
            --no-restore
